// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-my-orders.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_orders_default = defineTool({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the signed-in Skylands Transport user's orders (diesel and transport quotes), newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max number of orders to return (default 20)."),
    status: z.string().optional().describe(
      "Optional status filter, e.g. 'Inquiry Received', 'Order Approved', 'In Transit', 'Delivered'."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("quotes").select(
      "order_id, service, service_type, details, quantity, location, status, created_at, delivered_at"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-order.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_order_default = defineTool2({
  name: "get_order",
  title: "Get order details",
  description: "Look up one Skylands Transport order by its order ID (e.g. #SK-1001). Only returns the order if it belongs to the signed-in user.",
  inputSchema: {
    order_id: z2.string().min(1).describe("The order's public ID, e.g. '#SK-1001' or 'SK-1001'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const normalized = order_id.trim().startsWith("#") ? order_id.trim() : `#${order_id.trim()}`;
    const { data, error } = await supabaseForUser2(ctx).from("quotes").select(
      "order_id, service, service_type, details, quantity, location, status, created_at, delivered_at"
    ).eq("user_id", ctx.getUserId()).eq("order_id", normalized).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `Order ${normalized} not found.` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/tools/create-diesel-quote.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_diesel_quote_default = defineTool3({
  name: "create_diesel_quote",
  title: "Create a diesel quote",
  description: "Create a new diesel fuel quote for the signed-in Skylands Transport user. Returns the newly created order.",
  inputSchema: {
    liters: z3.number().positive().describe("Liters of diesel requested."),
    fuel_grade: z3.string().optional().describe("Fuel grade (e.g. '50ppm', '500ppm'). Optional."),
    delivery_location: z3.string().min(1).describe("Delivery location / address in South Africa."),
    note: z3.string().optional().describe("Optional additional note.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ liters, fuel_grade, delivery_location, note }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const details = [
      `${liters}L`,
      fuel_grade ? `Grade: ${fuel_grade}` : null,
      note ? `Note: ${note}` : null
    ].filter(Boolean).join(", ");
    const { data, error } = await supabaseForUser3(ctx).from("quotes").insert({
      order_id: "",
      user_id: ctx.getUserId(),
      service: "Diesel",
      service_type: "Diesel",
      details,
      quantity: `${liters}L`,
      location: delivery_location
    }).select(
      "order_id, service, details, quantity, location, status, created_at"
    ).single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        { type: "text", text: `Created order ${data.order_id} (Diesel, ${liters}L to ${delivery_location}).` }
      ],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/tools/create-transport-quote.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_transport_quote_default = defineTool4({
  name: "create_transport_quote",
  title: "Create a transport quote",
  description: "Create a new logistics/transport quote for the signed-in Skylands Transport user. Returns the newly created order.",
  inputSchema: {
    load_detail: z4.string().min(1).describe("What's being transported, e.g. 'General Cargo', 'Perishables', 'Hazmat'."),
    pickup: z4.string().min(1).describe("Pickup location."),
    dropoff: z4.string().min(1).describe("Drop-off location."),
    weight_class: z4.string().optional().describe("Weight class, e.g. 'Under 5 Tons', '5-10 Tons', 'Superlink 30+'."),
    note: z4.string().optional().describe("Optional additional note.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ load_detail, pickup, dropoff, weight_class, note }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const details = [
      load_detail,
      weight_class,
      `${pickup} \u2192 ${dropoff}`,
      note ? `Note: ${note}` : null
    ].filter(Boolean).join(", ");
    const { data, error } = await supabaseForUser4(ctx).from("quotes").insert({
      order_id: "",
      user_id: ctx.getUserId(),
      service: "Transport",
      service_type: "Transport",
      details,
      quantity: weight_class ?? null,
      location: `${pickup} \u2192 ${dropoff}`
    }).select(
      "order_id, service, details, quantity, location, status, created_at"
    ).single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        { type: "text", text: `Created order ${data.order_id} (Transport, ${pickup} \u2192 ${dropoff}).` }
      ],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser5(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_profile_default = defineTool5({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in Skylands Transport user's profile (name, phone, default address, email).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser5(ctx).from("profiles").select("full_name, phone_number, default_address, email").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kbkvrfnnxgfontzmxrjo";
var mcp_default = defineMcp({
  name: "skylands-transport-mcp",
  title: "Skylands Transport",
  version: "0.1.0",
  instructions: "Tools for Skylands Transport clients. Use `list_my_orders` and `get_order` to review the signed-in user's diesel and transport orders, `create_diesel_quote` and `create_transport_quote` to submit new quote requests, and `get_my_profile` to read the user's account details.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_my_orders_default,
    get_order_default,
    create_diesel_quote_default,
    create_transport_quote_default,
    get_my_profile_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
